CREATE TABLE DEAL.DEAL
(
    DEAL_ID             NUMBER(10) PRIMARY KEY NOT NULL,
    ENTERPRISE_DEAL_ID  NUMBER(10) NOT NULL,
    APPLIED_SCENARIO_ID NUMBER(10) NOT NULL
) ;

INSERT INTO DEAL.DEAL (DEAL_ID, ENTERPRISE_DEAL_ID, APPLIED_SCENARIO_ID) VALUES
    (1, 1, 1),
    (2, 2, 2),
    (3, 3, 3);
